[tool.poetry]
name = "openapi_client"
version = "1.0.0"
description = "OpenAPI Okta IP Ranges"
authors = ["OpenAPI Okta IP Ranges <blah+oapicf@cliffano.com>"]
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/oapicf/openapi-okta-ip-ranges"
keywords = ["OpenAPI", "OpenAPI-Generator", "OpenAPI Okta IP Ranges"]
include = ["openapi_client/py.typed"]

[tool.poetry.dependencies]
python = "^3.8"

urllib3 = ">= 1.25.3"
python-dateutil = ">=2.8.2"
pydantic = "^1.10.5, <2"
aenum = ">=3.1.11"

[tool.poetry.dev-dependencies]
pytest = ">=7.2.1"
tox = ">=3.9.0"
flake8 = ">=4.0.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"
